version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "we are building" 
      - run: sleep 5
  testa:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "we are testing a" 
      - run: sleep 5
  testb:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "we are testing b" 
      - run: sleep 5
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "we are deploying" 
      - run: sleep 5
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testa:
          requires:
            - build
      - testa:
          requires:
            - build
      - deploy:
          requires:
            - testa
            - testb

